Algoritmo "semnome"
//  Ler o sexo de uma pessoa (M,F) e imprimir uma mensagem
// informando se "É homem" ou se "É mulher".

Var
// Seção de Declarações das variáveis 
sexo: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Insira seu sexo (M) (F): ")
leia (sexo)

se sexo = "M" entao
   escreva ("Você é homem.")
senao
escreva ("Você é mulher.")
   fimse

Fimalgoritmo