Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/07/2024
Var
// Seção de Declarações das variáveis 
I, S: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto I <= 10 faça
         S <= S + I
         I <= I + 1
escreva (I)
fimenquanto

Fimalgoritmo